# Generated by Django 3.1.6 on 2021-02-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada'), ('P', 'SinSolución')], default='A', max_length=2),
        ),
    ]
