# Generated by Django 3.2 on 2021-05-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_auto_20210507_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], default='A', max_length=2),
        ),
    ]
